name: Build Base Image

on:
  pull_request:
    paths:
      - 'build/base/**'

jobs:
  build-base-image-php7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]
        librdkafka: [ 'v1.8.2' ]
        extrdkafka: [ '3.0.5', '3.1.2', '4.0.4', '4.1.2', '5.0.2' ]
        laravel: [ '6', '7', '8' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: build/base
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            LIBRDKAFKA_VERSION=${{ matrix.librdkafka }}
            EXT_RDKAFKA_VERSION=${{ matrix.extrdkafka }}
            LARAVEL_VERSION=${{ matrix.laravel }}
          push: true
          tags: arquivei/php-kafka-consumer:${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}

  build-base-image-php8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0' ]
        librdkafka: [ 'v1.8.2' ]
        extrdkafka: [ '5.0.2', '6.0.0' ]
        laravel: [ '7', '8', '9' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: build/base
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            LIBRDKAFKA_VERSION=${{ matrix.librdkafka }}
            EXT_RDKAFKA_VERSION=${{ matrix.extrdkafka }}
            LARAVEL_VERSION=${{ matrix.laravel }}
          push: true
          tags: arquivei/php-kafka-consumer:${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}

  build-base-image-php81:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]
        librdkafka: [ 'v1.8.2' ]
        extrdkafka: [ '5.0.2', '6.0.0' ]
        laravel: [ '8', '9' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: build/base
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            LIBRDKAFKA_VERSION=${{ matrix.librdkafka }}
            EXT_RDKAFKA_VERSION=${{ matrix.extrdkafka }}
            LARAVEL_VERSION=${{ matrix.laravel }}
          push: true
          tags: arquivei/php-kafka-consumer:${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}

