name: Build Base Image

on:
  pull_request:
    paths:
      - 'build/base/**'

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        librdkafka: [ 'v1.9.2', 'v2.5.0' ]
        extrdkafka: [ '4', '5', '6' ]
        laravel: [ '6', '7', '8', '9', '10', '11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: build/base
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            LIBRDKAFKA_VERSION=${{ matrix.librdkafka }}
            EXT_RDKAFKA_VERSION=${{ matrix.extrdkafka }}
            LARAVEL_VERSION=${{ matrix.laravel }}
          push: true
          tags: arquivei/php-kafka-consumer:${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}