name: Version test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [6, 8, 9]
    steps:
      - uses: actions/checkout@v2
      - name: Test Laravel[${{ matrix.laravel }}]
        run:
          make version-test-${{ matrix.laravel }}
