name: Version test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
        librdkafka: [v1.7.0]
        extrdkafka: [3.0.5, 3.1.2, 4.0.4, 5.0.2]
        laravel: [6, 7, 8]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
  run-tests-8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0"]
        librdkafka: [v1.7.0]
        extrdkafka: [5.0.0]
        laravel: [6, 7, 8]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
