name: Version test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        librdkafka: [ 'v1.9.2', 'v2.5.0' ]
        extrdkafka: [ '3.0.5', '3.1.2', '4.0.4', '4.1.2', '5.0.2', '6.0.2' ]
        laravel: [ '6', '7', '8', '9', '10', '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
