name: Version test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
        librdkafka: [v1.8.2]
        extrdkafka: [3.0.5, 3.1.2, 4.0.4, 4.1.2, 5.0.2]
        laravel: [6, 7, 8]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
  run-tests-8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0"]
        librdkafka: [v1.8.2]
        extrdkafka: [5.0.2, 6.0.0]
        laravel: [8, 9]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
  run-tests-8-laravel-7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0"]
        librdkafka: [v1.8.2]
        extrdkafka: [5.0.2]
        laravel: [7]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
  run-tests-8-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.1"]
        librdkafka: [v1.8.2]
        extrdkafka: [5.0.2, 6.0.0]
        laravel: [8, 9]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
  run-tests-8-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2"]
        librdkafka: [v1.8.2]
        extrdkafka: [5.0.2, 6.0.0]
        laravel: [8, 9, 10, 11]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
